version: '3.8'

services:
  cybersecurity-system:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/cybersecurity_db
    depends_on:
      - redis
      - postgres
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
    networks:
      - cybersecurity-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cybersecurity-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=cybersecurity_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cybersecurity-network
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:

networks:
  cybersecurity-network:
    driver: bridge
