name: Basic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Basic syntax check
      run: |
        python -m py_compile src/ai_models/threat_detector.py
        python -m py_compile src/data_collection/network_monitor.py
        python -m py_compile src/utils/helpers.py
        python -m py_compile src/alerting/alert_manager.py
        python -m py_compile src/dashboard/routes.py
        python -m py_compile src/real_time/stream_processor.py

    - name: Run basic tests
      run: |
        python -m pytest tests/test_basic.py -v || true

    - name: Check imports
      run: |
        python -c "import src.ai_models.threat_detector; print('AI models import OK')"
        python -c "import src.data_collection.network_monitor; print('Network monitor import OK')"
        python -c "import src.utils.helpers; print('Helpers import OK')"
        python -c "import src.alerting.alert_manager; print('Alert manager import OK')"
        python -c "import src.dashboard.routes; print('Dashboard routes import OK')"
        python -c "import src.real_time.stream_processor; print('Stream processor import OK')"
